# Generated by Django 5.2.14 on 2026-05-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(db_index=True, max_length=512)),
                ('town_city', models.CharField(blank=True, db_index=True, max_length=256)),
                ('county', models.CharField(blank=True, db_index=True, help_text='Treated as region for filtering (UK county or similar).', max_length=256)),
                ('type_rating', models.CharField(blank=True, max_length=256)),
                ('route', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['organisation_name'],
                'indexes': [models.Index(fields=['county', 'organisation_name'], name='companies_s_county_69610b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSponsorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('have_tried', models.BooleanField(default=False, help_text='Mark if you have already approached or applied here.')),
                ('tried_at', models.DateTimeField(blank=True, null=True)),
                ('what_i_know', models.TextField(blank=True, help_text='Your notes: context, contacts, reputation, etc.')),
                ('what_they_do', models.TextField(blank=True, help_text='What the company does (sector, products, hiring patterns).')),
                ('extra_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='companies.sponsor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User sponsor entries',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sponsor'), name='unique_user_sponsor_entry')],
            },
        ),
    ]
